#!/bin/sh

case "$DWMBLOCKS_BUTTON" in
1) notify-send "CPU hogs" "$(ps axch -o cmd:15,%cpu --sort=-%cpu | head)\\n(100% per core)" ;;
2) "$TERMINAL" -e "$EDITOR" "$0" ;;
3) setsid -f "$TERMINAL" -e top ;;
esac

sensors | awk '/^Core 0:/{print $3; exit}' | tr -d '+'
