#!/bin/sh

case "$DWMBLOCKS_BUTTON" in
1) notify-send "CPU usage" "$(ps axch -o cmd:16,%cpu --sort=-%cpu | head)" ;;
2) "$TERMINAL" -e "$EDITOR" "$0" >/dev/null 2>&1 ;;
3) setsid -f "$TERMINAL" -e top -u "${USER}" ;;
esac

sensors |
  awk -v ORS="" '/^Core 0:/{print " CPU: "$3};/^junction:/{print " GPU: "$2}' |
  tr -d '+'
