#!/bin/sh
# "🎤"
# "♬"

case "$DWMBLOCKS_BUTTON" in
1) setsid -f "$TERMINAL" -e pulsemixer ;;
2) "$TERMINAL" -e "$EDITOR" "$0" ;;
3) amixer set Master toggle ;;
6) amixer set Capture toggle ;;
esac

volstat="$(amixer get Master)"
echo "$volstat" | grep -m 1 -q "\[on\]" && printf "♬-"
# Append the piped command: "| tr -d '\n'" to the line below if your
# build of dwmblocks doesn't take care of '\n' chars
echo "$volstat" | grep -m 1 -o "\[[0-9]\+%\]" | sed "s/[^0-9]*//g;1q"

amixer get Capture | grep -m 1 -q "\[on\]" && printf " 🎤"
