-- Generated by nwg-displays on 2026-01-26 at 21:50:36. Do not edit manually.
hl.monitor({ output = "desc:Lenovo Group Limited 0x403D", mode = "1920x1200@60.0", position = "0x0", scale = 1.5 })
hl.monitor({ output = "desc:Philips Consumer Electronics Company 49M2C8900 AU42447000384", mode = "5120x1440@59.98", position = "1280x0", scale = 1.0 })