#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule sync --quiet --recursive
git submodule update --init --recursive

"${BASEDIR}/submodules/dotbot/${DOTBOT_BIN}" \
  --plugin-dir "${BASEDIR}/submodules/dotbot-gh-extension" \
  -d "${BASEDIR}" -c "${CONFIG}" "${@}"
