#!/bin/sh
### Helpful to help mount external devices/android devices.
### Requires bemenu, simple-mtpfs, and optionally udisks2.
### Prefers using udisks2 but falls back to mount/umount.
### Might not work for all kinds of Android phones (check:
### [Arch wiki android](https://wiki.archlinux.org/index.php/Android#Transferring_files)).

mount_drive() {
  drives="$(lsblk -nr |
    awk '$6!="disk" && $7=="" {print $1 " (" $4 ")"}')"
  # ask user to select drive
  selected_drive=$(printf "%s" "$drives" |
    bemenu -i -p "Drive to mount:" |
    sed -e 's/\s.*$//')
  # check if the selectiong is valid
  existance=$(printf "%s" "$drives" |
    sed -e 's/\s.*$//' |
    awk -v cmp_var="$selected_drive" '$0 == cmp_var')

  [ "$existance" ] && printf "%s" "$selected_drive"
}

umount_drive() {
  drives="$(lsblk -nr |
    awk '$6!="disk" && $7!="" {print $1 " (" $4 ")"}')"
  # ask user to select drive
  selected_drive=$(printf "%s" "$drives" |
    bemenu -i -p "Drive to umount:" |
    sed -e 's/\s.*$//')
  # check if the selectiong is valid
  existance=$(printf "%s" "$drives" |
    sed -e 's/\s.*$//' |
    awk -v cmp_var="$selected_drive" '$0 == cmp_var')

  [ "$existance" ] && printf "%s" "$selected_drive"
}

# check for udisksctl
fallback="$(command -v udisksctl)"
[ -z "$fallback" ] && echo "udisksctl not found, falling back to mount/umount..."
op=$(printf "Mount drive\nUmount drive\nMount android\nUmount android" |
  bemenu -i -p "What to do:") || exit
[ -z "$op" ] && exit

case "$op" in
"Mount drive")
  selected_drive="$(mount_drive)"
  [ -z "$selected_drive" ] && exit 1

  if [ "$fallback" ]; then
    # use udisks2
    if udisksctl mount -b "/dev/${selected_drive}"; then
      # technically this could be "optimized" but the code would look uglier imo
      mount_point="$(udisksctl info -b "/dev/$selected_drive" | grep -iF MountPoints | awk '{print $2}')"
      notify-send -e "DMOUNT SUCCESS" "$selected_drive partition mounted to $mount_point" &
    else
      notify-send -e "DMOUNT FAILURE" "Can't mount $selected_drive partition" &
    fi
  else
    # fallback
    sudo -A mkdir "/mnt/${selected_drive}"
    if sudo -A mount "/dev/${selected_drive}" "/mnt/${selected_drive}"; then
      mount_point="/mnt/${selected_drive}"
      notify-send -e "DMOUNT SUCCESS" "$selected_drive partition mounted to $mount_point" &
    else
      notify-send -e "DMOUNT FAILURE" "Can't mount $selected_drive partition" &
    fi
  fi
  ;;
"Umount drive")
  selected_drive="$(umount_drive)"
  [ -z "$selected_drive" ] && exit 1

  if [ "$fallback" ]; then
    # use udisks2
    mount_point="$(udisksctl info -b "/dev/$selected_drive" | grep -iF MountPoints | awk '{print $2}')"
    if udisksctl unmount -b "/dev/${selected_drive}"; then
      notify-send -e "DMOUNT SUCCESS" "$selected_drive partition umounted from $mount_point" &
    else
      notify-send -e "DMOUNT FAILURE" "Can't umount $selected_drive partition from $mount_point" &
    fi
  else
    # fallback
    mount_point="/mnt/${selected_drive}"
    if sudo -A umount "/dev/${selected_drive}"; then
      sudo -A rmdir /mnt/"$selected_drive"
      notify-send -e "DMOUNT SUCCESS" "$selected_drive partition umounted from $mount_point" &
    else
      notify-send -e "DMOUNT FAILURE" "Can't umount $selected_drive partition from $mount_point" &
    fi
  fi
  ;;
"Mount android")
  selected_drive=$(simple-mtpfs -l |
    bemenu -i -p "Drive to mount:" |
    sed s/:.*$//)

  existance=$(simple-mtpfs -l |
    sed s/:.*$// |
    awk -v cmp_var="$selected_drive" '$0 == cmp_var')
  [ -z "$existance" ] && exit

  android_mount_path="/run/media/${USER}/Android${selected_drive}"
  mkdir "$android_mount_path"
  simple-mtpfs --device "$selected_drive" "$android_mount_path"
  notify-send -e "DMOUNT SUCCESS" "Android partition $selected_drive mounted to $android_mount_path" &
  ;;
"Umount android")
  selected_drive=$(simple-mtpfs -l |
    bemenu -i -p "Drive to umount:" |
    sed s/:.*$//)

  existance=$(simple-mtpfs -l |
    sed s/:.*$// |
    awk -v cmp_var="$selected_drive" '$0 == cmp_var')
  [ -z "$existance" ] && exit

  android_mount_path="/run/media/${USER}/Android${selected_drive}"
  fusermount -u "$android_mount_path"
  rmdir "$android_mount_path"
  if [ -d "$android_mount_path" ]; then
    notify-send -e "DMOUNT FAILURE" "Can't umount $selected_drive android partition from from $android_mount_path" &
  else
    notify-send -e "DMOUNT SUCCESS" "Android partition $selected_drive umounted from $android_mount_path" &
  fi
  ;;
esac
