#!/bin/sh
### Menu to help mount external devices/android devices
### Requires dmenu

op=$(printf "Mount drive\nUmount drive\nMount android\nUmount android" |
  dmenu -i -p "What to do:") || exit

[ -z "$op" ] && exit

case "$op" in
"Mount drive")
  selected_drive=$(lsblk -nr |
    awk '$6!="disk" && $7=="" {print $1 " " $4}' |
    dmenu -i -p "Drive to mount:" |
    sed -e 's/\s.*$//')

  existance=$(lsblk -nr |
    awk '$6!="disk" && $7=="" {print $1 " " $4}' |
    sed -e 's/\s.*$//' |
    awk -v cmp_var="$selected_drive" '$0 == cmp_var')
  [ -z "$existance" ] && exit

  sudo -A mkdir /mnt/"$selected_drive"
  sudo -A mount /dev/"$selected_drive" /mnt/"$selected_drive"
  notify-send "DMOUNT SUCCESS" "$selected_drive partition mounted to /mnt/$selected_drive" &
  ;;
"Umount drive")
  selected_drive=$(lsblk -nr |
    awk '$6!="disk" && $7!="" {print $1 " " $4}' |
    dmenu -i -p "Drive to umount:" |
    sed -e 's/\s.*$//')

  existance=$(lsblk -nr |
    awk '$6!="disk" && $7!="" {print $1 " " $4}' |
    sed -e 's/\s.*$//' |
    awk -v cmp_var="$selected_drive" '$0 == cmp_var')
  [ -z "$existance" ] && exit

  sudo -A umount /dev/"$selected_drive"
  sudo -A rmdir /mnt/"$selected_drive"
  if [ -d /mnt/"$selected_drive" ]; then
    notify-send "DMOUNT FAILURE" "Can't umount $selected_drive partition from from /mnt/$selected_drive" &
  else
    notify-send "DMOUNT SUCCESS" "$selected_drive partition umounted from /mnt/$selected_drive" &
  fi
  ;;
"Mount android")
  selected_drive=$(simple-mtpfs -l |
    dmenu -i -p "Drive to mount:" |
    sed s/:.*$//)

  existance=$(simple-mtpfs -l |
    sed s/:.*$// |
    awk -v cmp_var="$selected_drive" '$0 == cmp_var')
  [ -z "$existance" ] && exit

  mkdir "$HOME"/Android"$selected_drive"
  simple-mtpfs --device "$selected_drive" "$HOME"/Android"$selected_drive"
  notify-send "DMOUNT SUCCESS" "Android partition $selected_drive mounted to ~/Android$selected_drive" &
  ;;
"Umount android")
  selected_drive=$(simple-mtpfs -l |
    dmenu -i -p "Drive to umount:" |
    sed s/:.*$//)

  existance=$(simple-mtpfs -l |
    sed s/:.*$// |
    awk -v cmp_var="$selected_drive" '$0 == cmp_var')
  [ -z "$existance" ] && exit

  fusermount -u "$HOME"/Android"$selected_drive"
  rmdir "$HOME"/Android"$selected_drive"
  if [ -d "$HOME"/Android"$selected_drive" ]; then
    notify-send "DMOUNT FAILURE" "Can't umount $selected_drive android partition from from ~/Android$selected_drive" &
  else
    notify-send "DMOUNT SUCCESS" "Android partition $selected_drive umounted from ~/Android$selected_drive" &
  fi
  ;;
esac
