#!/bin/sh
### My password helper script

set -eu

CURL="curl --connect-timeout 5"
bemenu="bemenu -i -l 5"
remote="http://10.77.77.77"

login_cmd="$CURL $remote/api/login.php"

## Login Funtion ##
if [ "$($login_cmd)" = "failure" ]; then
	if [ "$($login_cmd -X POST -F "password=$(printf "" | bemenu -x -p 'PIZ_HID Login:')")" = "authenticated" ]; then
		notify-send "DPIZHID" "Piz_Hid authenticated" &
	else
		notify-send "DPIZHID" "Piz_Hid authentication failed" &
	fi

	exit
fi

## PIZ_HID Communication ##
entry_list="$($CURL $remote/api/list.php)"
entry_sel="$(printf "%s\n---Lock---\n---Shutdown---\n---Multiline---\n---ClipPass---" "$entry_list" |
	$bemenu -p "Entry:")" || exit

## PIZ_HID Data Processing ##
case "$entry_sel" in
"---Lock---")
	$CURL "$remote/api/logout.php"
	;;
"---Shutdown---")
	$CURL "$remote/api/shutdown.php"
	;;
"---Multiline---")
	## list non-passwd info in entry and clip it ##
	entry_sel="$(printf "%s" "$entry_list" | $bemenu -p "Multiline:")" || exit
	entry_contents="$($CURL "$remote/api/multiline.php?entry=$entry_sel" |
		$bemenu -p "Multiline:")" || exit

	[ "$entry_contents" ] && printf "%s" "$entry_contents" | wl-copy
	;;
"---ClipPass---")
	## insert pass into clipboard ##
	entry_sel="$(printf "%s" "$entry_list" | $bemenu -p "ClipPass:")" || exit
	$CURL "$remote/api/password.php?entry=${entry_sel}&clip" | wl-copy
  notify-send "DPIZHID" "ClipPass" &
	;;
*)
	## auto-write pass and clip user ##
	$CURL "$remote/api/password.php?entry=${entry_sel}" | wl-copy
	;;
esac
