#!/bin/sh

# Based on Luke Smith's dmenurecord

# Usage:
# `$0`: Ask for recording type via dmenu
# `$0 screencast`: Record both audio and screen
# `$0 video`: Record only screen
# `$0 audio`: Record only audio
# `$0 kill`: Kill existing recording
#
# If there is already a running instance, user will be prompted to end it.

RECORDPID_FILE="/tmp/recordingpid"
OUTPUT_DIR="$HOME/Videos"
mkdir -p "$OUTPUT_DIR"

savepid() {
  echo $! >"$RECORDPID_FILE"
}

killrecording() {
  recpid="$(cat $RECORDPID_FILE)"
  # kill with SIGTERM, allowing finishing touches.
  kill -15 "$recpid"
  rm -f "$RECORDPID_FILE"

  # even after SIGTERM, ffmpeg may still run, so SIGKILL it.
  sleep 3
  kill -9 "$recpid"
  exit
}

screencast() {
  ffmpeg -y \
    -f x11grab \
    -framerate 60 \
    -s "$(xdpyinfo | grep dimensions | awk '{print $2;}')" \
    -i "$DISPLAY" \
    -f alsa -i default \
    -r 30 \
    -c:v libx264rgb -crf 0 -preset ultrafast -c:a flac \
    "$OUTPUT_DIR/screencast-$(date '+%y%m%d-%H%M-%S').mkv" &
  savepid
}

video() {
  ffmpeg \
    -f x11grab \
    -s "$(xdpyinfo | grep dimensions | awk '{print $2;}')" \
    -i "$DISPLAY" \
    -c:v libx264 -qp 0 -r 30 \
    "$OUTPUT_DIR/video-$(date '+%y%m%d-%H%M-%S').mkv" &
  savepid
}

webcamhidef() {
  ffmpeg \
    -f v4l2 \
    -i /dev/video0 \
    -video_size 1920x1080 \
    "$OUTPUT_DIR/webcam-$(date '+%y%m%d-%H%M-%S').mkv" &
  savepid
}

webcam() {
  ffmpeg \
    -f v4l2 \
    -i /dev/video0 \
    -video_size 640x480 \
    "$OUTPUT_DIR/webcam-$(date '+%y%m%d-%H%M-%S').mkv" &
  savepid
}

audio() {
  ffmpeg \
    -f alsa -i default \
    -c:a flac \
    "$OUTPUT_DIR/audio-$(date '+%y%m%d-%H%M-%S').flac" &
  savepid
}

askrecording() {
  asktoend

  op=$(printf "screencast\nvideo\naudio\nwebcam\nwebcam (hi-def)" | dmenu -i -p "Select recording mode:" || exit)
  case "$op" in
  "screencast") screencast ;;
  "audio") audio ;;
  "video") video ;;
  "webcam") webcam ;;
  "webcam (hi-def)") webcamhidef ;;
  esac
}

asktoend() {
  if [ -f "$RECORDPID_FILE" ]; then
    response=$(printf "No\nYes" | dmenu -i -p "Recording still active. End recording?" || return)
    [ "$response" = "Yes" ] && killrecording
  fi
}

case "$1" in
"screencast") screencast ;;
"audio") audio ;;
"video") video ;;
"kill") killrecording ;;
*) askrecording ;;
esac
