#!/bin/sh
### my dmenu run wrapper

# CONSTS #
# find related constants
search_dir="$HOME"
min_dep=2
max_dep=5

# cache file related constants
max_size=10
cachedir=${XDG_DATA_HOME:-"$HOME/.local/share"}
hist_file="$cachedir/mdmenu_run" # history file
[ -f "$hist_file" ] || touch "$hist_file"

# list commands in cache ordered by number of usages
#hist_l=$(sort "$hist_file" | uniq -c | sort -r | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}')
hist_l="$(cat "$hist_file")"
# list of directories (and strip $search_dir from it)
#dirs_l="$(find "$search_dir" -maxdepth $min_dep -type d | sed 's|^/home/joao||')"

save_hist() {
  # save command in history file
  newentry="$1"

  (
    printf "%s\n" "$newentry"
    printf "%s" "$hist_l" | grep -vxF "$newentry"
  ) | head -n $max_size >"$hist_file.tmp"

  mv "$hist_file.tmp" "$hist_file"
}

sel=$( (
  printf "%s\n" "$hist_l"
  dmenu_path | grep -vxF "$hist_l"
  printf "%s\n%s" "---directories----" "---files---"
) | dmenu "$@" || exit)

[ -z "$sel" ] && exit

case "$sel" in
"---directories----")
  # trigger directories searching
  sel="$(find "$search_dir" -mindepth $min_dep -maxdepth $max_dep -type d | sed 's|^/home/joao||' | dmenu "$@")"
  [ "$sel" ] && "$TERMINAL" -e "$FILE" "$search_dir/$sel"
  ;;
"---files---")
  # trigger file searching
  sel="$(find "$search_dir" -mindepth $min_dep -maxdepth $max_dep -type f | sed 's|^/home/joao||' | dmenu "$@")"
  [ "$sel" ] && "$TERMINAL" -e "$FILE" "$search_dir/$sel"
  ;;
/*)
  # cd to directory or file location
  "$TERMINAL" -e "$FILE" "$search_dir/$sel"
  ;;
*\;)
  # exec command in a new terminal
  printf "%s %s" "$TERMINAL -e" "$sel" | "${SHELL:-"/bin/sh"}" "-i" &
  save_hist "$sel"
  ;;
*)
  # exec command
  printf "%s" "$sel" | "${SHELL:-"/bin/sh"}" "-i" &
  save_hist "$sel"
  ;;
esac
