-- Generated by nwg-displays on 2026-06-12 at 23:51:32. Do not edit manually.

hl.monitor({
    output = "desc:Lenovo Group Limited 0x403D",
    mode = "1920x1200@60.0",
    position = "4778x1080",
    scale = 1.0
})
hl.monitor({
    output = "desc:Samsung Electric Company S24R35x H4TNA00797",
    mode = "1920x1080@60.0",
    position = "5760x0",
    scale = 1.0
})
hl.monitor({
    output = "desc:Hewlett Packard HP x23LED CNC047Q8YJ",
    mode = "1920x1080@60.0",
    position = "3840x0",
    scale = 1.0
})
