#!/bin/bash

while read -r file; do
	case "$1" in
	"c") # Copy file
		destdir="$(bemenu -l 20 -i -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
		[ -z "$destdir" ] && exit
		cp "$file" "$destdir" && notify-send -u low -i "$(readlink -f "$file")" "SXIV" "file copied to $destdir." &
		;;
	"C") # Copy file to clipboard
		convert "$file" png:- | wl-copy
		;;
	"m") # Move file
		destdir="$(bemenu -l 20 -i -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
		[ -z "$destdir" ] && exit
		mv "$file" "$destdir" && notify-send -u low -i "$(readlink -f "$file")" "SXIV" "file moved to $destdir." &
		;;
	"r") # Rotate clockwise
		convert -rotate 90 "$file" "$file" ;;
	"R") # Rotate anti-clockwise
		convert -rotate -90 "$file" "$file" ;;
	"f") # Invert Image
		convert -flop "$file" "$file" ;;
	"y") # Copy image location
		printf "%s" "$file" | wl-copy && notify-send "$file copied to clipboard" & ;;
	"Y") # Copy image location (following links)
		printf "%s" "$(readlink -f "$file")" | wl-copy && notify-send "$(readlink -f "$file") copied to clipboard" & ;;
	"d") # File deletion with bemenu confirmation
		[ "$(printf "No\nYes" | bemenu -i -p "Really delete $file?")" == "Yes" ] && rm "$file" && notify-send "$file deleted." & ;;
	"G") # Open file in Gimp
		gimp "$file" & ;;
	esac
done
