#!/bin/sh
### Preview images using kitty graphics protocol
### Use [ctpv](https://github.com/NikitaIvanovV/ctpv) for everything else

draw() {
  kitten icat --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
  exit 1
}

file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

case "$(file -Lb --mime-type "$file")" in 
  image/*)
    draw "$file"
    ;;
esac

ctpv "$file"
