#!/bin/sh
### Simple script to open a [codi](https://github.com/metakirby5/codi.vim)
### notebook in Neovim.

if [ $# -eq 0 ]; then
  syntax="python"
else
  syntax="$1"
  shift
fi

nvim -c "let g:startify_disable_at_vimenter = 1 | set bt=nofile ls=0 noru nonu nornu | hi ColorColumn ctermbg=NONE | hi VertSplit ctermbg=NONE | hi NonText ctermfg=0 | Codi $syntax" "$@"
