#!/bin/sh

# directory to get files and directories from
homedir_f="$HOME"
homedir_d="$homedir_f"
# directory to copy files to
destdir_f="$HOME/.config/homedir_conf"
# directory to copy directories to
destdir_d="$HOME/.config"

# command line arguments
case "$1" in
  "-i" | "-r")
    temp="$homedir_f"
    homedir_f="$destdir_f"
    destdir_f="$temp"

    temp="$homedir_d"
    homedir_d="$destdir_d"
    destdir_d="$temp"
    ;;
  *)
    if [ "$1" ]; then
      printf "Unkown option: %s" "$1"
      exit 1
    fi
    ;;
esac

# list of files to copy (can be path's from 'homedir')
file_l=".bash_completion
.bash_profile
.bashrc
.profile
.xinitrc"

# list of directories to copy (can be path's from 'homedir')
dir_l=".local/bin"

printf "Going to copy the following files from %s to %s:\n%s\n" "$homedir_f" "$destdir_f" "$file_l"
printf "Going to copy the following directories from %s to %s:\n%s\n" "$homedir_d" "$destdir_d" "$dir_l"
printf "Do you want to preceed? [Y/n] "
read -r ans

# exit if answer isn't yes or nothing
if [ "$ans" != "y" ] && [ "$ans" != "Y" ] && [ "$ans" ]; then
  printf "Process aborted by user.\n"
  exit 0
fi

for file in $file_l; do
  if ! test -r "$homedir_f/$file"; then
    printf "File %s doesn't exist or isn't readable. Skipping..\n" "$homedir_f/$file"
    continue
  else
    cp "$homedir_f/$file" "$destdir_f"
  fi
done
printf "File copying process finished.\n"

for direc in $dir_l; do
  if ! test -d "$homedir_d/$direc"; then
    printf "Directory %s doesn't exist or isn't readable. Skipping..\n" "$homedir_d/$direc"
    continue
  else
    for f in "$homedir_d/$direc"/*; do
      cp -r "$f" "$destdir_d/Scripts"
    done
  fi
done
printf "Directory copying process finished.\n"
