#!/bin/sh
### Toggles dunst's notifications.

was_paused="$(dunstctl is-paused)"

if [ "$was_paused" = "false" ]; then
  dunstctl set-paused true
else
  dunstctl set-paused false
  notify-send -e "Dunst ON"
fi

