#!/bin/sh

while true
do
        VOL=$(amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')	#VOL as %
        LOCALTIME=$(date +%a\ %d-%m-%Y\ %H:%M)					#Time as dd-mm-yyyy hh:mm
        TEMP="$(($(cat /sys/class/thermal/thermal_zone0/temp) / 1000))C"	#Temp as tC (t is int degrees)
	#BAT="$(printf "%s" "$(acpi -b)" | awk -F ',' '{print $2}' | awk '{$1=$1};1')"	#Battery level

	xsetroot -name "$TEMP $VOL $LOCALTIME"					#Show the info
	#xsetroot -name "B-$BAT $TEMP $VOL $LOCALTIME"

	sleep 3s								#Wait 3s before starting the next update
done
