#!/bin/sh
### Old script I used to use to take fullscreen screenshots and as a snipping tool.
### Too slow for my liking so I switched to [maim](https://github.com/naelstrof/maim)
### via the **maim_handler** script.
### Pass any/amount of argument(s) to make a snipping tool instead.
### Requires imagemagick.

ptr_name="$(mktemp -u "$HOME/Pictures/screenshots/$(date '+%d-%m-%y').XXX.png")"

if [ -z "$1" ]
then
	import -window root "$ptr_name"
	notify-send -u low -i "$ptr_name" "Print Screen" "Print saved to ~/Pictures/screenshots" &
else
	import "$ptr_name"
	notify-send -u low -i "$ptr_name" "Snipping Tool" "Snip saved to ~/Pictures/screenshots" &
fi

