#!/bin/sh
### Recovers from a lockscreen crash in Hyprland.
### Run from another TTY, then switch back to TTY running
### Hyprland to unlock.
### Currently assumes the lockscreen program is noctalia

set -eu

hyprctl --instance 0 eval 'hl.clear_crashed_lockscreen()'
sleep 5
noctalia msg session lock
echo "Done. Switch back to original TTY to unlock."
