#!/bin/sh

#requires maim and xclip
#pass any/amount of argument(s) to make a snipping tool instead
#either take a fullscreen screenshot and save it in a file or take a snip and pass it t the clipboard

#save_location="$HOME/Pictures/screenshots/"
save_location="$HOME/Scripts/di"

if [ "$1" ]
then
	maim -u -m 10 -s -o | xclip -selection clipboard -t image/png
	notify-send -u low "Snipping Tool" "Snip saved to clipboard" &
else
	file_name="$(date +%s).png"
	maim -u -m 10 "$save_location/$file_name"
	notify-send -u low -i "$save_location/$file_name" "Print Screen" "Print saved to $save_location" &
fi

