#!/bin/sh
### requires maim and xclip
### Args:
### "snip" - take a snip and pass it to the clipboard
### "picker" - color picker (needs work)
### "current" - snip current active window
### "screenshot" - take a fullscreen screenshot and save it in a file
### no args - dmenu arg selection

parse_arg() {
  case "$1" in
  "snip")
    # Sniping tool
    maim -u -s -B -m 7 | xclip -selection clipboard -t image/png
    notify-send -u low "Snipping Tool" "Snip saved to clipboard" &
    ;;
  "picker")
    # Color picker
    color_info=$(maim -u -s -B -t 0 | convert - -resize 1x1\! -format \
      '%[pixel:p{0,0}]' txt:- | tail -n 1 | awk -F' ' '{print $3}')
    printf "%s" "$color_info" | xclip -selection clipboard
    notify-send "Color Picker" "Color is $color_info" &
    ;;
  "current")
    maim -m 7 -i "$(xdotool getactivewindow)" | xclip -selection clipboard -t image/png
    ;;
  "screenshot")
    # Fullscreen screenshot
    save_location="${SCREENSHOT_SAVEDIR:-$HOME/Pictures/screenshots/}"
    [ -d "$save_location" ] || mkdir -p "$save_location"

    file_name="$(date +%s).png"
    maim -u -m 10 "$save_location/$file_name"
    notify-send -u low -i "$save_location/$file_name" "Print Screen" "Print saved to $save_location" &
    ;;
  *)
    exit 1
    ;;
  esac
}

[ "$1" ] && parse_arg "$1" || parse_arg "$(printf "snip\\npicker\\ncurrent\\nscreenshot" | dmenu -i -p "What to do?")"
