#!/bin/sh
### Script that calls maxima on a terminal. It uses **rlwrap** for
### history and built-ins file (also for getline). It is based on **rmaxima**
### but it has a few improvements.
### Depends on [maxima](http://maxima.sourceforge.net/).

# check if rlwrap is installed
RLWRAP=rlwrap
if [ ! "$(command -v "$RLWRAP")" ]; then
  echo "$0 error: mmaxima requires rlwrap." >& 1
  echo "rlwrap is available from <https://github.com/hanslub42/rlwrap>." >& 1
  exit 1
fi

# get the maxima builtins list file
MAXIMA_BUILTINS="$MAXIMA_USERDIR"/maxima-builtins-list.txt
if [ ! -f "$MAXIMA_BUILTINS" ]; then
  MAXIMA_SHAREDIR="/usr/share/maxima/5.43.0/share"
  MAXIMA_BUILTINS="$MAXIMA_SHAREDIR"/maxima-builtins-list.txt
fi

# set history file location
MAXIMA_HISTORY="$MAXIMA_USERDIR"/maxima-history

# run maxima
if [ -f "$MAXIMA_BUILTINS" ]; then
  exec rlwrap -a -c -b '(){}[].,*/+-=&^$#@\;|´`:' -H "$MAXIMA_HISTORY" -f "$MAXIMA_BUILTINS" -r -D 2 maxima --disable-readline "$@"
else
  echo "$0: failed to locate list of built-in symbols; go ahead without it."
  echo "$0: (I thought it might be $MAXIMA_USERDIR/maxima-builtins-list.txt or $MAXIMA_BUILTINS but there are no such files.)"
  exec rlwrap -a -c -b '(){}[].,*/+-=&^$#@\;|´`:' -H "$MAXIMA_HISTORY" -r -D 2 maxima --disable-readline "$@"
fi
