#!/bin/sh
### Measure screen area. Basically a wrapper for hacksaw with notifications.  
### Depends on hacksaw (but could use something like slop as well).

notify-send "Screen measure" "$(hacksaw -f 'X: %x -- Y: %y\nWidth: %w\nHeight: %h')"
