#!/bin/sh
### Script that can:
### - Take full-screen screen-shots (saves them in a previously specified folder);
### - Screen-shot a selection of the screen (places the image in the clipboard);
### - Output color information of a selection (saves RGB color code in clipboard and show a notification for it too).
### 
### Args:
### - "snip" - take a snip and pass it to the clipboard (just clicking get the full clicked window);
### - "picker" - color picker (needs work);
### - "current" - screenshot current screen;
### - "current save" - screenshot current screen and auto save it to $SCREENSHOT_SAVEDIR directory;
### - "full" - screenshot fullscreen screenshot;
### - no args - dmenu arg selection.
### Depends on [flameshot](https://github.com/flameshot-org/flameshot),
### [colorpicker](https://github.com/Jack12816/colorpicker), xclip, and dmenu.

parse_arg() {
  case "$1" in
  "snip")
    # Sniping tool
    # intentionally unquoted
    flameshot gui
    ;;
  "picker")
    # Color picker
    color="$(colorpicker --short --one-shot --preview)"
    printf "%s" "$color" | xclip -selection clipboard
    notify-send "Color Picker" "Color is $color" &
    ;;
  "current")
    flameshot screen
    ;;
  "current save")
    save_location="${SCREENSHOT_SAVEDIR:-$HOME/Pictures/screenshots}/"
    flameshot screen -p "$save_location"
    ;;
  "full")
    # Fullscreen screenshot
    flameshot full
    ;;
  *)
    exit 1
    ;;
  esac
}

if [ "$1" ]; then
  parse_arg "$1"
else 
  parse_arg "$(printf "snip\\npicker\\ncurrent\\ncurrent save\\nfull" | dmenu -i -p "What to do?")"
fi
