#!/bin/sh
### Spawns an instance of the st terminal with a fixed geometry and name:
###
### - Class: $TERM
### - Instance: st-float
### - Position: 180x40
### - X-offset: 300
### - Y-offset: 16

# how many monitors are connected
scrn_cnt=2

scrn_width="$(xdpyinfo | grep dimensions | uniq | awk '{print $2}' | cut -d 'x' -f1)"
single_w=$((scrn_width / scrn_cnt))
# get mouse location
eval "$(xdotool getmouselocation --shell)"

# get current screen
curr_scrn=1
while [ "$X" -gt $((single_w * curr_scrn)) ]; do
  curr_scrn=$((curr_scrn + 1))
done
curr_scrn=$((curr_scrn - 1))

wid="$(xdotool search --classname st-float)"
if [ -z "$wid" ]; then
  # not spawned, so spawn window
  setsid st -n "st-float" -g "180x40+$((curr_scrn * single_w + 300))+16"
else
  map_state="$(xwininfo -id "$wid" | grep "Map State:" | cut -d':' -f2 | tr -d ' ')"
  if [ "$map_state" = "IsViewable" ]; then
    xdotool windowunmap "$wid"
  else
    xdotool windowmap "$wid"
  fi
fi
