#!/bin/sh
### Starts the Wayland compositor using uwsm.
### Checks may-start, presents selection menu, then starts default session.

# if uwsm check may-start; then
#   exec uwsm start -- hyprland.desktop
# fi

if uwsm check may-start && uwsm select; then
  exec systemd-cat -t uwsm_start uwsm start default
fi
