#!/bin/sh

#
# Sway
#
#exec sway

#
# Hyprland
#
Hyprland
systemctl --user stop hyprland-session.target

#
# DWL
#
# This should run inside (pass a script to DWL):
# dbus-update-activation-environment --systemd --all; systemctl --user start dwl-session.target
#
#dbus-run-session dwl
#systemctl --user stop dwl-session.target
