#!/bin/sh
### This scripts opens all image files inside a directory with sxiv.
### If a file is provide, all the other files inside it's folder are also opened with sxiv
### Requires find, xargs and sxiv

[ $# -eq 0 ] && echo "Usage: ${0##*/} Image Files/Dirs" && exit 1

abspath() {
  case "$1" in
  /*) printf "%s\n" "$1" ;;
  *) printf "%s\n" "$PWD/$1" ;;
  esac
}

listfiles() {
  find -L "$(dirname "$target")" -maxdepth 1 -type f -iregex \
    '.*\(jpe?g\|bmp\|png\|gif\|webp\)$' -print0 | sort -zg
}

target="$(abspath "$1")"
if [ ! -f "$target" ]; then
  sxiv "$@" >/dev/null 2>&1
  exit $?
fi

count="$(listfiles | grep -m 1 -Zz -n -Fx "$target" | cut -d: -f1)"
[ -z "$count" ] && echo "No such file or directory" && exit 1

listfiles | xargs -r0 sxiv -n "$count" >/dev/null 2>&1
