$primary = rgb(69d3ff)
$surface = rgb(111415)
$secondary = rgb(b4cad6)
$error = rgb(ffb4ab)
$tertiary = rgb(c6c2ea)
$surface_lowest = rgb(0c0f10)

general {
    col.active_border = $primary
    col.inactive_border = $surface
}

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
