#!/bin/sh
### Feed script a url or file location.
### If image or gif, view in sxiv,
### if video, watch in mpv
### if music file or pdf, download,
### otherwise it opens link in browser.
### Based on https://github.com/LukeSmithxyz/voidrice/blob/master/.local/bin/linkhandler

if [ $# -eq 0 ]; then
  echo "Usage: ${0##*/} URL"
  exit 1
fi

# If no url given. Opens browser. For using script as $BROWSER.
[ -z "$1" ] && {
  "$BROWSER"
  exit
}

case "$1" in
*mkv | *webm | *mp4 )#| *youtube.com/watch* | *youtube.com/playlist* | *youtu.be* | *hooktube.com* | *bitchute.com*)
  setsid mpv --input-ipc-server="/tmp/mpvsoc$(date +%s)" -quiet "$1" >/dev/null 2>&1 &
  ;;
*png | *jpg | *jpe | *jpeg | *gif)
  curl -sL "$1" >"/tmp/$(echo "$1" | sed "s/.*\///")" && sxiv -a "/tmp/$(echo "$1" | sed "s/.*\///")" >/dev/null 2>&1 &
  ;;
*mp3 | *flac | *opus | *mp3?source*)
  setsid curl -LO "$1" >/dev/null 2>&1 &
  ;;
*)
  if [ -f "$1" ]; then
    "$TERMINAL" -e "$EDITOR $1"
  else
    setsid "$BROWSER" "$1" >/dev/null 2>&1 &
  fi
  ;;
esac
