#!/bin/sh

# better defaults
alias df="df -h"
alias dmesg="dmesg -HL"
alias du="du -ch"
alias ffmpeg="ffmpeg -hide_banner"
alias mkdir="mkdir -p -v"
alias dir="dir --color=auto"
alias vdir="vdir --color=auto"
alias diff="diff --color=auto"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"

# new commands
alias ll='$LS --group-directories-first -lgh --git'
# go to git repo root directory
alias gr='git rev-parse --show-toplevel && cd "$(git rev-parse --show-toplevel)"'
