#!/bin/bash
# FUNCRC #
# The functions defined in this file are using the non-standard `function foo {}`
# instead of `foo() {}` so it is easier for me use this file both on bash and on fish

function bashrc {
  "$EDITOR" "$HOME/.bashrc"
  source "$HOME/.bashrc"
}

function fishrc {
  "$EDITOR" "$HOME/.config/fish/config.fish"
  source "$HOME/.config/fish/config.fish"
}

function aliasrc {
  "$EDITOR" "$HOME/.config/aliasrc"
  source "$HOME/.config/aliasrc"
}

function funcrc {
  "$EDITOR" "$HOME/.config/funcrc"
  source "$HOME/.config/funcrc"
}

# opens lf and cd's to the current folder on exit
function lfcd {
  tmp="$(mktemp)"
  lf -last-dir-path="$tmp" "$@"
  # cleanup terminal window name changes (not standard)
  printf "\033]0;st\007" > /dev/tty

  if [ -f "$tmp" ]; then
    dir="$(cat "$tmp")"
    rm -f "$tmp"

    [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
  fi
}

function h {
  # https://samizdat.dev/help-message-for-shell-scripts/
  sed -rn 's/^### ?//;T;p' "$1"
}

function cf {
  inputStr="$*"
  find "$SCRIPTS"/* "$HOME/.config"/* -type f -print0 |
    fzf --read0 --print0 -q "$inputStr" |
    xargs -r -0 "$EDITOR"
}

function notes {
  find "$NOTES"/* -type f -print0 | fzf --read0 --print0 |
    xargs -r -0 "$EDITOR"
}

function help {
  path="$(find "$SCRIPTS"/* -type f -print0 | fzf --read0 --print0)"
  [ ! -f "$path" ] && return
  sed -rn 's/^### ?//;T;p' "$path"
}

function clndepl {
  while true; do
    clndep --noconfirm || return 0;
  done
}

function internetdolucassimulator {
  while true; do
    amixer set Capture toggle >/dev/null 2>&1;
  done
}
