#!/bin/bash
### The functions defined in this file are using the non-standard `function foo {}`
### instead of `foo() {}` so it is easier for me use this file both on bash and on fish

# opens lf and cd's to the current folder on exit
function lfcd {
  tmp="$(mktemp)"
  lf -last-dir-path="$tmp" "$@"
  # cleanup terminal window name changes (not standard)
  printf "\033]0;st\007" >/dev/tty

  if [ -f "$tmp" ]; then
    dir="$(cat "$tmp")"
    rm -f "$tmp"

    [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && cd "$dir"
  fi
}

function h {
  # https://samizdat.dev/help-message-for-shell-scripts/
  sed -rn 's/^### ?//;T;p' "$1"
}

function cf {
  inputStr="$*"
  find "$SCRIPTS" "$HOME/.dotfiles" "$HOME/.config" -maxdepth 3 -type f -print0 |
    fzf --read0 --print0 -q "$inputStr" |
    xargs -r -0 "$EDITOR"
}

function notes {
  find "$NOTES" -type f -print0 | fzf --read0 --print0 |
    xargs -r -0 "$EDITOR"
}

function help {
  path="$(find "$SCRIPTS"/* -type f -print0 | fzf --read0 --print0)"
  [ ! -f "$path" ] && return
  sed -rn 's/^### ?//;T;p' "$path"
}

function clndepl {
  while true; do
    clndep --noconfirm || return 0
  done
}

# find package and install it
function fpkg {
  pkg="$( (pacman -Slq && yay -Slq) | fzf)"
  [ -z "$pkg" ] && return 0
  if pacman -Slq | grep -q -w "^${pkg}$"; then
    sudo pacman -Syu "$pkg"
  else
    yay -Syu "$pkg"
  fi
}

function internetdolucassimulator {
  while true; do
    amixer set Capture toggle >/dev/null 2>&1
  done
}

function httpstatus {
  code="$1"
  if [[ -z $code ]]; then
    echo "Usage: httpstatus <status code>"
    exit 0
  fi
  curl --silent "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/${code}" | htmlq --text ".main-page-content > .section-content" | sed -e 's/  //g'
}

function compress_video {
  for f in "$@"; do
    ffmpeg -i "$f" -vcodec libx265 -crf 30 "${f}.mp4"
  done
}

# clipboard
function copy {
  cat | wl-copy
}

function paste {
  wl-paste
}

function xcopy {
  cat | xclip -selection clipboard
}

function xpaste {
  xclip -selection clipboard -o
}
